### ISSUE TITLE
Cannot execute binary

### ISSUE THREAD

**Issue by toynbeeidea** [simoninns/DomesdayDuplicator#79]
I've built DomesdayDuplicator and dddconv - I've even successfully used the former, once.  Now, whenever I try to launch, I get the message "cannot execute binary file."  No further details, just doesn't feel like it today, I guess?  Files are executable:  

-rwxr-xr-x 1 erik erik 48568 Mar 12 11:32 dddconv

**Comment by simoninns** [comment]
Google tells me that the error is caused due to running a 64-bit executable on a 32 bit OS.  Confirm that you have the correct supported installation of Ubuntu 18.04 LTS - If your machine is so old it can only support a 32-bit OS, then it's probably not suitable for use as a capture system.  If you have installed a 32 bit version of Ubuntu by mistake, replace it with the 64-bit version.
